#pragma once

#include "lvgl.h"

#include "ui_feed_model.h"

typedef enum {
    UI_FEED_ICON_SMALL = 0, /* the two outer neighbours */
    UI_FEED_ICON_MEDIUM,    /* the two inner neighbours */
    UI_FEED_ICON_LARGE,     /* the selected tile */
    UI_FEED_ICON_SIZE_COUNT,
} ui_feed_icon_size_t;

/* Drawn bitmaps rather than font symbols: LVGL's built-in set has no antenna,
 * no flash drive and no DLNA mark, so internet radio, FM and Yandex Music all
 * ended up as the same music note. The bitmaps are alpha-only, which lets the
 * carousel recolour one image per slot - accent in the middle, dimmer towards
 * the edges. Generated by tools/gen_feed_icons.py. */
const lv_image_dsc_t *ui_feed_icon_image(ui_feed_item_t item, ui_feed_icon_size_t size);
