/* Generated by tools/gen_feed_icons.py - do not edit by hand.
 *
 * Alpha-only bitmaps for the home screen carousel. LVGL blends an A8 image
 * with the object's image_recolor, so one bitmap per size serves the accent
 * centre and both dimmed neighbours.
 */

#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t ui_feed_icon_podcasts_24;
extern const lv_image_dsc_t ui_feed_icon_podcasts_32;
extern const lv_image_dsc_t ui_feed_icon_podcasts_44;
extern const lv_image_dsc_t ui_feed_icon_podcasts_48;
extern const lv_image_dsc_t ui_feed_icon_podcasts_64;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_24;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_32;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_44;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_48;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_64;
extern const lv_image_dsc_t ui_feed_icon_sd_card_24;
extern const lv_image_dsc_t ui_feed_icon_sd_card_32;
extern const lv_image_dsc_t ui_feed_icon_sd_card_44;
extern const lv_image_dsc_t ui_feed_icon_sd_card_48;
extern const lv_image_dsc_t ui_feed_icon_sd_card_64;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_24;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_32;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_44;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_48;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_64;
extern const lv_image_dsc_t ui_feed_icon_radio_24;
extern const lv_image_dsc_t ui_feed_icon_radio_32;
extern const lv_image_dsc_t ui_feed_icon_radio_44;
extern const lv_image_dsc_t ui_feed_icon_radio_48;
extern const lv_image_dsc_t ui_feed_icon_radio_64;
extern const lv_image_dsc_t ui_feed_icon_dlna_24;
extern const lv_image_dsc_t ui_feed_icon_dlna_32;
extern const lv_image_dsc_t ui_feed_icon_dlna_44;
extern const lv_image_dsc_t ui_feed_icon_dlna_48;
extern const lv_image_dsc_t ui_feed_icon_dlna_64;
extern const lv_image_dsc_t ui_feed_icon_spark_24;
extern const lv_image_dsc_t ui_feed_icon_spark_32;
extern const lv_image_dsc_t ui_feed_icon_spark_44;
extern const lv_image_dsc_t ui_feed_icon_spark_48;
extern const lv_image_dsc_t ui_feed_icon_spark_64;
extern const lv_image_dsc_t ui_feed_icon_settings_24;
extern const lv_image_dsc_t ui_feed_icon_settings_32;
extern const lv_image_dsc_t ui_feed_icon_settings_44;
extern const lv_image_dsc_t ui_feed_icon_settings_48;
extern const lv_image_dsc_t ui_feed_icon_settings_64;
extern const lv_image_dsc_t ui_feed_icon_volume_16;
extern const lv_image_dsc_t ui_feed_icon_heart_16;
extern const lv_image_dsc_t ui_feed_icon_heart_filled_16;
extern const lv_image_dsc_t ui_feed_icon_heart_slash_16;
extern const lv_image_dsc_t ui_feed_icon_music_note_64;
extern const lv_image_dsc_t ui_feed_icon_music_note_107;
