/* Generated by tools/gen_feed_icons.py - do not edit by hand.
 *
 * Alpha-only bitmaps for the home screen carousel. LVGL blends an A8 image
 * with the object's image_recolor, so one bitmap per size serves the accent
 * centre and both dimmed neighbours.
 */

#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t ui_feed_icon_podcasts_24;
extern const lv_image_dsc_t ui_feed_icon_podcasts_32;
extern const lv_image_dsc_t ui_feed_icon_podcasts_44;
extern const lv_image_dsc_t ui_feed_icon_podcasts_48;
extern const lv_image_dsc_t ui_feed_icon_podcasts_64;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_24;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_32;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_44;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_48;
extern const lv_image_dsc_t ui_feed_icon_usb_stick_64;
extern const lv_image_dsc_t ui_feed_icon_sd_card_24;
extern const lv_image_dsc_t ui_feed_icon_sd_card_32;
extern const lv_image_dsc_t ui_feed_icon_sd_card_44;
extern const lv_image_dsc_t ui_feed_icon_sd_card_48;
extern const lv_image_dsc_t ui_feed_icon_sd_card_64;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_24;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_32;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_44;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_48;
extern const lv_image_dsc_t ui_feed_icon_bluetooth_64;
extern const lv_image_dsc_t ui_feed_icon_radio_24;
extern const lv_image_dsc_t ui_feed_icon_radio_32;
extern const lv_image_dsc_t ui_feed_icon_radio_44;
extern const lv_image_dsc_t ui_feed_icon_radio_48;
extern const lv_image_dsc_t ui_feed_icon_radio_64;
extern const lv_image_dsc_t ui_feed_icon_dlna_24;
extern const lv_image_dsc_t ui_feed_icon_dlna_32;
extern const lv_image_dsc_t ui_feed_icon_dlna_44;
extern const lv_image_dsc_t ui_feed_icon_dlna_48;
extern const lv_image_dsc_t ui_feed_icon_dlna_64;
extern const lv_image_dsc_t ui_feed_icon_spark_24;
extern const lv_image_dsc_t ui_feed_icon_spark_32;
extern const lv_image_dsc_t ui_feed_icon_spark_44;
extern const lv_image_dsc_t ui_feed_icon_spark_48;
extern const lv_image_dsc_t ui_feed_icon_spark_64;
extern const lv_image_dsc_t ui_feed_icon_settings_24;
extern const lv_image_dsc_t ui_feed_icon_settings_32;
extern const lv_image_dsc_t ui_feed_icon_settings_44;
extern const lv_image_dsc_t ui_feed_icon_settings_48;
extern const lv_image_dsc_t ui_feed_icon_settings_64;
extern const lv_image_dsc_t ui_feed_icon_volume_16;
extern const lv_image_dsc_t ui_feed_icon_heart_16;
extern const lv_image_dsc_t ui_feed_icon_heart_filled_16;
extern const lv_image_dsc_t ui_feed_icon_heart_slash_16;
extern const lv_image_dsc_t ui_feed_icon_music_note_64;
extern const lv_image_dsc_t ui_feed_icon_music_note_107;
extern const lv_image_dsc_t ui_feed_icon_clear_day_16;
extern const lv_image_dsc_t ui_feed_icon_clear_day_20;
extern const lv_image_dsc_t ui_feed_icon_clear_day_24;
extern const lv_image_dsc_t ui_feed_icon_clear_day_32;
extern const lv_image_dsc_t ui_feed_icon_clear_night_16;
extern const lv_image_dsc_t ui_feed_icon_clear_night_20;
extern const lv_image_dsc_t ui_feed_icon_clear_night_24;
extern const lv_image_dsc_t ui_feed_icon_clear_night_32;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_day_16;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_day_20;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_day_24;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_day_32;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_night_16;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_night_20;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_night_24;
extern const lv_image_dsc_t ui_feed_icon_partly_cloudy_night_32;
extern const lv_image_dsc_t ui_feed_icon_cloudy_16;
extern const lv_image_dsc_t ui_feed_icon_cloudy_20;
extern const lv_image_dsc_t ui_feed_icon_cloudy_24;
extern const lv_image_dsc_t ui_feed_icon_cloudy_32;
extern const lv_image_dsc_t ui_feed_icon_fog_16;
extern const lv_image_dsc_t ui_feed_icon_fog_20;
extern const lv_image_dsc_t ui_feed_icon_fog_24;
extern const lv_image_dsc_t ui_feed_icon_fog_32;
extern const lv_image_dsc_t ui_feed_icon_rain_16;
extern const lv_image_dsc_t ui_feed_icon_rain_20;
extern const lv_image_dsc_t ui_feed_icon_rain_24;
extern const lv_image_dsc_t ui_feed_icon_rain_32;
extern const lv_image_dsc_t ui_feed_icon_snow_16;
extern const lv_image_dsc_t ui_feed_icon_snow_20;
extern const lv_image_dsc_t ui_feed_icon_snow_24;
extern const lv_image_dsc_t ui_feed_icon_snow_32;
extern const lv_image_dsc_t ui_feed_icon_sleet_16;
extern const lv_image_dsc_t ui_feed_icon_sleet_20;
extern const lv_image_dsc_t ui_feed_icon_sleet_24;
extern const lv_image_dsc_t ui_feed_icon_sleet_32;
extern const lv_image_dsc_t ui_feed_icon_thunderstorm_16;
extern const lv_image_dsc_t ui_feed_icon_thunderstorm_20;
extern const lv_image_dsc_t ui_feed_icon_thunderstorm_24;
extern const lv_image_dsc_t ui_feed_icon_thunderstorm_32;
