#pragma once

#include <stdbool.h>
#include <stddef.h>

#define STATION_CATALOG_PATH "/littlefs/config/stations.csv"
#define STATION_CATALOG_TEMP_PATH "/littlefs/config/stations.tmp"
/* What the catalogue holds. The count is the number the on-device list can be
 * scrolled through and the number the two-digit index in it can name; the two
 * lengths are what a station line may carry.
 *
 * The whole catalogue is one array of these - 35 KB at these numbers - so it
 * lives in PSRAM rather than in .bss. Both buffers on the playlist path (the
 * file read in internet_radio.c and the upload limit in web_server.c) are
 * derived from these three numbers rather than typed, so raising the count
 * again cannot leave a buffer behind that silently truncates the file. */
#define STATION_CATALOG_MAX_ENTRIES 99
#define STATION_CATALOG_NAME_MAX_LEN 96
#define STATION_CATALOG_URL_MAX_LEN 256
/* The file name of the station's picture in /littlefs/radio_img, generated by
 * the device when the picture is uploaded. A name only: it is joined to that
 * one directory and may not travel out of it, which is why the parser refuses
 * a separator or a leading dot. */
#define STATION_CATALOG_ICON_MAX_LEN 32
/* Where those pictures live. One directory, flat, one file per station. */
#define STATION_ICON_DIR "/littlefs/radio_img"
/* One line at its longest: name, separator, url, the letter, the picture,
 * newline, and room to spare. */
#define STATION_CATALOG_LINE_MAX_LEN \
    (STATION_CATALOG_NAME_MAX_LEN + STATION_CATALOG_URL_MAX_LEN + \
     STATION_CATALOG_ICON_MAX_LEN + 8U)
/* The whole file at its longest, with the terminator. */
#define STATION_CATALOG_TEXT_MAX_LEN \
    (STATION_CATALOG_MAX_ENTRIES * STATION_CATALOG_LINE_MAX_LEN + 1U)

typedef struct {
    char name[STATION_CATALOG_NAME_MAX_LEN];
    char url[STATION_CATALOG_URL_MAX_LEN];
    /* Which name the station line shows: the one kept here, or the one the
     * stream announces. Written as `L` or `S` in the file's third column -
     * see station_catalog_parse_line() for why it is a letter and not the 0
     * or 1 it holds here. */
    int flag;
    /* Empty when the station has no picture of its own: the fourth column is
     * optional, and a playlist written for another device has no column to
     * put one in. */
    char icon[STATION_CATALOG_ICON_MAX_LEN];
} station_catalog_entry_t;

typedef struct {
    station_catalog_entry_t entries[STATION_CATALOG_MAX_ENTRIES];
    size_t count;
} station_catalog_t;

/* Whether a picture's file name may be joined to /littlefs/radio_img. Letters,
 * digits, dot, dash and underscore, and never a leading dot: everything else
 * is a way out of that directory. An empty name is valid and means no
 * picture. */
bool station_catalog_icon_is_valid(const char *icon);
bool station_catalog_parse_line(const char *line, station_catalog_entry_t *entry);
bool station_catalog_load_text(const char *text, station_catalog_t *catalog);
bool station_catalog_find_by_url(const station_catalog_t *catalog, const char *url,
                                 size_t *index);
bool station_catalog_append_if_missing(station_catalog_t *catalog,
                                       const station_catalog_entry_t *entry);
