#pragma once

/* ESP32-S3 QFN56 board wiring, revision 1. */
#define BOARD_TFT_WIDTH 320
#define BOARD_TFT_HEIGHT 240
/* Verified on the connected TFT: blue data is rendered red with MADCTL RGB. */
#define BOARD_TFT_RGB_ORDER_BGR 1
#define BOARD_TFT_SWAP_XY 1
/* Rotate the current landscape image by 180 degrees. */
#define BOARD_TFT_MIRROR_X 0
#define BOARD_TFT_MIRROR_Y 0
#define BOARD_LCD_WAIT_FOR_TRANSFER 1
#define BOARD_INPUT_USE_INTERNAL_PULLUPS 1
#define BOARD_TFT_CS_GPIO 10
#define BOARD_TFT_DC_GPIO 47
#define BOARD_TFT_MOSI_GPIO 11
#define BOARD_TFT_SCLK_GPIO 12
#define BOARD_TFT_BACKLIGHT_GPIO 2

#define BOARD_ENCODER_RIGHT_GPIO 5
#define BOARD_ENCODER_LEFT_GPIO 7
#define BOARD_ENCODER_BUTTON_GPIO 6

#define BOARD_BUTTON_F1_GPIO 45
#define BOARD_BUTTON_F2_GPIO 21
#define BOARD_BUTTON_F3_GPIO 46
#define BOARD_BUTTON_F4_GPIO 9

#define BOARD_I2S_DOUT_GPIO 16
#define BOARD_I2S_BCLK_GPIO 18
#define BOARD_I2S_LRCK_GPIO 17
#define BOARD_AUDIO_DEFAULT_SAMPLE_RATE 44100
#define BOARD_AUDIO_BITS_PER_SAMPLE 16
#define BOARD_AUDIO_CHANNEL_COUNT 2
#define BOARD_I2S_SLOT_BIT_WIDTH 16
/* 8 x 512 frames provide about 92.9 ms of buffering at 44.1 kHz. */
#define BOARD_I2S_DMA_DESC_NUM 8
#define BOARD_I2S_DMA_FRAME_NUM 512
#define BOARD_I2S_AUTO_CLEAR_AFTER_CB 1
#define BOARD_I2S_PRELOAD_SILENCE 1

#define BOARD_USB_DM_GPIO 19
#define BOARD_USB_DP_GPIO 20
