#pragma once

#include <stddef.h>
#include <stdint.h>

#include "board_display_profile.h"

/* The picture shown while the rest of the firmware starts, in place of the
 * solid test fill the display used to come up with.
 *
 * Stored run-length encoded as (count, RGB565) pairs in raster order rather
 * than as a pixel array: the panel raw is 150 KB of the 3 MB app partition,
 * and this picture - a dark ground, a few smooth gradients, 479 distinct
 * colours - comes to under a third of that. It is `const`, so it lives in
 * flash and costs no RAM at all: board_display_draw_rgb565() copies through
 * its own band buffer with a byte swap and never hands the source to DMA,
 * which is what makes drawing straight out of rodata legal here.
 *
 * Generated by tools/gen_boot_splash.py; regenerate rather than editing.
 */

/* The shape the picture was drawn at is not stated here any more. It used to
 * be, as a pair of constants board.c checked against TFT_WIDTH and TFT_HEIGHT,
 * which worked while there were exactly two shapes and one flag to tell them
 * apart. The generated file now carries an arm per panel shape, selected by the
 * panel's own size, and checks its own encoded pixel count against the panel -
 * so the data proves its shape rather than a hand-written constant claiming
 * it, and a shape nobody has drawn is a compile error naming itself. */

extern const uint16_t boot_splash_rle[];
extern const size_t boot_splash_rle_pairs;
