#pragma once

#include <stddef.h>
#include <stdint.h>

/* The picture shown while the rest of the firmware starts, in place of the
 * solid test fill the display used to come up with.
 *
 * Stored run-length encoded as (count, RGB565) pairs in raster order rather
 * than as a pixel array: 320x240 raw is 150 KB of the 3 MB app partition,
 * and this picture - a dark ground, a few smooth gradients, 479 distinct
 * colours - comes to under a third of that. It is `const`, so it lives in
 * flash and costs no RAM at all: board_display_draw_rgb565() copies through
 * its own band buffer with a byte swap and never hands the source to DMA,
 * which is what makes drawing straight out of rodata legal here.
 *
 * Generated by tools/gen_boot_splash.py; regenerate rather than editing.
 */

#define BOOT_SPLASH_WIDTH 320
#define BOOT_SPLASH_HEIGHT 240

extern const uint16_t boot_splash_rle[];
extern const size_t boot_splash_rle_pairs;
